name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check if commit message includes #upload
      id: check_commit_message
      run: echo ::set-output name=contains_upload::$(if [[ $(git log -1 --pretty=%B) =~ '#upload' ]]; then echo true; else echo false; fi)

    - name: Checkout repository
      uses: actions/checkout@v2
      if: steps.check_commit_message.outputs.contains_upload == 'true'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust to the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        SECRET_HOST_NAME: ${{ secrets.SECRET_HOST_NAME }}
        SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
        SECRET_USER_NAME: ${{ secrets.SECRET_USER_NAME }}
      run: |
        python cicd/script.py 
