name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check if commit message includes #upload
        id: check_commit_message
        run: |
          echo "Checking if the latest commit message contains #upload..."

          # Ensure you are in a Git repository
          if [ ! -d ".git" ]; then
              echo "fatal: not a git repository (or any of the parent directories): .git"
              exit 1
          fi

          # Check the latest commit message for '#upload'
          if [[ $(git log -1 --pretty=%B) =~ '#upload' ]]; then
              contains_upload=true
          else
              contains_upload=false
          fi

          # Set the output using Environment Files
          echo "contains_upload=$contains_upload" >> $GITHUB_ENV

      - name: Display contains_upload output
        run: echo "contains_upload is ${{ env.contains_upload }}"

      - name: Fail if contains_upload is false
        if: env.contains_upload == 'false'
        run: |
          echo "Commit message contains #upload. Stopping the pipeline."
          exit 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust to the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SECRET_HOST_NAME: ${{ secrets.SECRET_HOST_NAME }}
          SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
          SECRET_USER_NAME: ${{ secrets.SECRET_USER_NAME }}
        run: |
          python cicd/script.py 
